[dmenu]
# Assuming your .DOTFILES are symlinked to your ~/.config/ directory
dmenu_command = rofi -dmenu -theme /home/goku/.config/rofi/wifi-top-right.rasi -i -p "Networks"
compact = True

[editor]
terminal = kitty
gui_if_available = True