general {
    lock_cmd = pidof hyprlock || hyprlock      
    before_sleep_cmd = loginctl lock-session    
    after_sleep_cmd = hyprctl dispatch dpms on  
}

# 1. Screen Dimming (Optional but recommended)
listener {
    timeout = 150                                # 2.5 mins
    on-timeout = brightnessctl -s set 10         # Dim screen
    on-resume = brightnessctl -r                 # Restore brightness
}


# 2. Screen Lock
listener {
    timeout = 270                                # 4.5 mins
    on-timeout = loginctl lock-session           # Lock screen
}

# 3. System Suspend
listener {
    timeout = 300                                # 5 mins
    on-timeout = systemctl suspend               # Suspend the system
}
