general {
    lock_cmd = pidof hyprlock || hyprlock       # Avoid starting multiple hyprlock instances
    before_sleep_cmd = loginctl lock-session    # Ensure the session is locked before sleeping
    after_sleep_cmd = hyprctl dispatch dpms on  # Avoid needing to press a key twice to wake the screen
}

# 1. Screen Dimming (Optional but recommended)
listener {
    timeout = 150                                # 2.5 mins
    on-timeout = brightnessctl -s set 10         # Dim screen
    on-resume = brightnessctl -r                 # Restore brightness
}

# 2. Warning Notification
listener {
    timeout = 240                                # 4 mins
    # Sends a critical notification that stays on screen for 10 seconds
    on-timeout = notify-send "System Sleep" "System will go to sleep in 60 seconds!" -u critical -t 10000
}

# 3. Screen Lock
listener {
    timeout = 270                                # 4.5 mins
    on-timeout = loginctl lock-session           # Lock screen
}

# 4. System Suspend
listener {
    timeout = 300                                # 5 mins
    on-timeout = systemctl suspend               # Suspend the system
}
