# Catppuccin Mocha
foreground              #cdd6f4
background              #1e1e2e
selection_foreground    #1e1e2e
selection_background    #f5e0dc
cursor                  #f5e0dc
cursor_text_color       #1e1e2e
active_border_color     #b4befe
inactive_border_color   #6c7086
